spring:
  datasource:
    url: jdbc:h2:file:.//xtremax_clinic
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Makassar
